version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(dependencies)"
    reviewers:
      - "kennylajara"
    labels:
      - "open-reason: auto"
      - "scope: dependencies"
      - "type: chore"
